name: Deploy PickForMe Server to Dev

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Start SSH agent with deploy keys
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.REPO_DEPLOY_KEY }}

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      - name: Ensure latest develop HEAD
        run: |
          git checkout develop
          git pull origin develop

      - name: Set Git remote to SSH
        run: git remote set-url origin git@github.com:Si-gongan/pickforme.git

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.19.5"

      - name: Deploy to EC2
        id: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ${{ secrets.DEV_EC2_USERNAME }}
          key: ${{ secrets.DEV_EC2_SSH_KEY }}
          script: |
            set -e

            source ~/.nvm/nvm.sh
            nvm install 20.19.5
            nvm use 20.19.5

            cd /home/ubuntu/pickforme
            git fetch origin
            git checkout develop
            git config pull.rebase false
            git pull origin develop
            cd back
            npm install
            npm run build
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi
            pm2 start pm2.json

      - name: Create and push tags
        if: steps.deploy.outcome == 'success'
        run: |
          TAG="server-dev-$(TZ=Asia/Seoul date +'%y%m%d-%H%M')"
          echo "Generated tag: $TAG"
          git tag "$TAG"
          git tag -fa server-dev-latest -m "latest dev server tag" "$TAG"
          git push origin "$TAG"
          git push --force origin server-dev-latest
